MODEL:
    META_ARCHITECTURE: "PoseSOR"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]
    WEIGHTS: ""
    PE: "APE"
    BACKBONE:
        NAME: "ResNeXt50"
        NUM_FEATURES: (256,512,1024,2048)
        FEATURE_KEYS: ["res2", "res3", "res4", "res5"]
    NECK:
        NAME: "FPN"
    SIS_HEAD:
        NAME: "TransformerDecoder"
        NUM_BLOCKS: 6
        KEY_FEATURES: ["res5", "res4", "res3"]
        MASK_KEY: "res2"
    ACTOR_INTERACTION:
        NAME: "PAI"
        NUM_LAYERS: 1
        NUM_BLOCKS: 3
        MASK_KEY: "res2"
        KEY_FEATURE: "res3"
        SCENE_BINS: [4, 4]
    POSE_SHIFT:
        NAME: "PDR"
        MASK_KEY: "res3"
        NUM_DIRECTIONS: 8
    COMMON:
        EMBED_DIM: 256
        NUM_HEADS: 8
        HIDDEN_DIM: 2048
        DROPOUT_ATTN: 0.0
        DROPOUT_FFN: 0.0
        NUM_JOINTS: 17
        NUM_QUERIES: 100
        MAX_RANK_LEVEL: 20
        TOPK_QUERIES: 8
LOSS:
    MASK_CE_COST: 1.0
    MASK_DICE_COST: 1.0
    OBJ_POS: 1.0
    OBJ_NEG: 0.1
    MASK_COST: 5.0
    PARTITION_COST: 5.0
    BBOX_L1_COST: 5.0
    BBOX_GIOU_COST: 2.0
    CLS_COST: 10.0
    JOINT_COST: 1000.0
    HEATMAP_COST: 100.0
    JOINT_CLS_COST: 10.0
    RANK_COST: 0.1
    PART_RANK_COST: 0.1
    NUM_POINTS: 12544
    SIGMA: 0.01
DATASETS:
    TRAIN: ("assr_train",)
    TEST: ("assr_test",)
    ROOT: "assets/datasets"
DATALOADER:
    NUM_WORKERS: 4
SOLVER:
    AMP:
        ENABLED: true
    BACKBONE_MULTIPLIER: 1.0
    BASE_LR: 0.00005
    CHECKPOINT_PERIOD: 10000
    CLIP_GRADIENTS:
        CLIP_TYPE: full_model
        CLIP_VALUE: 5.0
        ENABLED: true
        NORM_TYPE: 2.0
    GAMMA: 0.1
    IMS_PER_GPU: 8
    LR_SCHEDULER_NAME: WarmupMultiStepLR
    MOMENTUM: 0.9
    OPTIMIZER: ADAMW
    STEPS: (30000,)
    MAX_ITER: 50000
    REFERENCE_WORLD_SIZE: 0
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 100
    WEIGHT_DECAY: 0.0001
INPUT:
    TRAIN_IMAGE_SIZE: 768
    TEST_IMAGE_SIZE: 768
    DYNAMIC_SIZES: [[704, 704], [736, 736], [768, 768], [800, 800]]
OUTPUT_DIR: "output/"
DEBUG:
    DEBUG_DIR: "debug/"
    TICK_PERIOD: 1000
    TOKEN: 0
TEST:
    EVAL_PERIOD: 5000
    # METRICS_OF_INTEREST: ["mae", "acc", "fbeta", "iou", "sa_sor", "sor", "ap", "ar", "top1", "top2", "top3", "top4", "top5", "jacc", "jae"]
    METRICS_OF_INTEREST: ["sa_sor", "sor", "mae", "jae"]
    THRESHOLD: 0.5
    OBJ_THRESHOLD: 0.1
    MASKNESS_THRESHOLD: 0.95
    EXPECTED_RESULTS: []
    PRECISE_BN:
        ENABLED: false
        NUM_ITER: 200
    AUG:
        ENABLED: false
    UPPER_BOUND: false
    EVAL_SAVE: false
VERSION: 2
